"""empty message

Revision ID: 2ec63fc91a80
Revises: 1662b99a587f
Create Date: 2021-01-02 16:13:01.228976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ec63fc91a80'
down_revision = '1662b99a587f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('worship_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_seat_worship_id_worship'), 'worship', ['worship_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('worship', schema=None) as batch_op:
        batch_op.add_column(sa.Column('curnum', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worship', schema=None) as batch_op:
        batch_op.drop_column('curnum')

    with op.batch_alter_table('seat', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_seat_worship_id_worship'), type_='foreignkey')
        batch_op.drop_column('worship_id')

    # ### end Alembic commands ###
